"""create tabel users

Revision ID: 28b69eae478a
Revises: 
Create Date: 2021-01-17 13:16:52.174121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b69eae478a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=230), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('app_google_play', sa.String(length=120), nullable=False),
    sa.Column('keyword_ig', sa.String(length=120), nullable=False),
    sa.Column('keyword_twitter', sa.String(length=120), nullable=False),
    sa.Column('app_apps_store', sa.String(length=120), nullable=False),
    sa.Column('nama_aplikasi', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.BigInteger(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
