"""create tabel sources

Revision ID: 44496ac4215c
Revises: 28b69eae478a
Create Date: 2021-01-17 13:24:33.058007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44496ac4215c'
down_revision = '28b69eae478a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources')
    # ### end Alembic commands ###
