"""create tabel api_config

Revision ID: ea26dd8bc767
Revises: de8e2396d118
Create Date: 2021-01-17 13:28:39.640453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea26dd8bc767'
down_revision = 'de8e2396d118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('API__config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=True),
    sa.Column('url_api', sa.String(length=500), nullable=True),
    sa.Column('param1', sa.String(length=500), nullable=True),
    sa.Column('param2', sa.String(length=500), nullable=True),
    sa.Column('consumer_key', sa.String(length=500), nullable=True),
    sa.Column('consumer_secret', sa.String(length=500), nullable=True),
    sa.Column('access_token', sa.String(length=500), nullable=True),
    sa.Column('access_token_secret', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('API__config')
    # ### end Alembic commands ###
