"""create tabel posts

Revision ID: f430b05c9540
Revises: 44496ac4215c
Create Date: 2021-01-17 13:25:11.200943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f430b05c9540'
down_revision = '44496ac4215c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=230), nullable=False),
    sa.Column('user_avatar', sa.String(length=255), nullable=False),
    sa.Column('post', sa.String(length=500), nullable=False),
    sa.Column('tanggal_post', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('link_review', sa.String(length=500), nullable=False),
    sa.Column('rating', sa.String(length=1), nullable=False),
    sa.Column('sentiment', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
